PROGRAM SCORES
IMPLICIT NONE

!Variable declarations
INTEGER,DIMENSION(10) :: SCORE
INTEGER :: i
CHARACTER(len=1) :: GRADE
CHARACTER(len=12) :: REMARK

!student scores
SCORE  = (/85, 62, 45, 91, 38, 74, 55, 88, 61, 47/)

!Print table heading
PRINT'(A)', 'STUDENT    SCORE    GRADE    REMARK'

DO i = 1, 10

!Grade classification
IF (SCORE(i) >= 80) THEN
GRADE = 'A'
REMARK = 'DISTINCTION'

ELSE IF (SCORE(i) >= 60) THEN
GRADE = 'B'
REMARK = 'CREDIT'

ELSE IF (SCORE(i) >= 40) THEN
GRADE = 'C'
REMARK = 'PASS'

ELSE
GRADE = 'F'
REMARK = 'FAIL'
END IF
!Formatted output
PRINT'(I5,5X,I5,5X,A,5X,A)', i, SCORE(i), GRADE, REMARK

END DO

END PROGRAM SCORES

!EDWARD_KWAKU_SOLOMON
!6313624
